#include "frontend/mac/MacFrontEnd.h"

#include "app/ApplicationController.h"
#include "frontend/mac/SpeecherBridge.h"

// Generated by swiftc from src/frontend/mac/swift, which is why the Swift target
// has to build before this one.
#import "SpeecherUI-Swift.h"

#include <QDesktopServices>
#include <QUrl>

namespace speecher {

struct MacFrontEnd::Native {
    SpeecherBridge *bridge = nil;
    SpeecherMainWindow *window = nil;
};

MacFrontEnd::MacFrontEnd(ApplicationController *controller)
    : m_controller(controller)
    , m_qt(controller)
    , m_native(std::make_unique<Native>())
{
    m_native->bridge = [[SpeecherBridge alloc] initWithController:controller];
    // The schema names the commands an Action row offers; what they do belongs
    // to the front end, as it does on Qt.
    m_native->bridge.settingsSchema.actionTriggered = ^(NSString *rowId) {
        const QString id = QString::fromNSString(rowId);
        if (id == QStringLiteral("runSetup")) {
            controller->showSetupAssistant();
            return;
        }
        if (id == QStringLiteral("openReleases")) {
            QDesktopServices::openUrl(
                QUrl(QStringLiteral("https://github.com/firemonster612/speecher/releases")));
        }
    };
}

MacFrontEnd::~MacFrontEnd() = default;

// An empty page id leaves the window on whichever page it was showing, which
// for a window that has just been made is the dictation page.
void MacFrontEnd::showWindow(const QString &pageId)
{
    if (!m_native->window) {
        m_native->window = [[SpeecherMainWindow alloc] initWithBridge:m_native->bridge];
    }
    [m_native->window showWithPage:pageId.toNSString()];
    // frontEndReady defers its work by a turn of the event loop, which is what
    // lets the window this call just ordered front draw first.
    m_controller->frontEndReady();
}

void MacFrontEnd::showMainWindow()
{
    showWindow(QString());
}

// One window: the settings are the rest of its sidebar.
void MacFrontEnd::showSettingsWindow()
{
    showWindow(QStringLiteral("general"));
}

void MacFrontEnd::showSetupAssistant()
{
    m_qt.showSetupAssistant();
}

bool MacFrontEnd::captureMainWindow(const QString &path)
{
    return m_native->window && [m_native->window captureToPath:path.toNSString()];
}

void MacFrontEnd::showDictationError(const QString &message)
{
    m_qt.showDictationError(message);
}

void MacFrontEnd::alert()
{
    m_qt.alert();
}

} // namespace speecher
