#include "frontend/mac/MacFrontEnd.h"

#include "app/ApplicationController.h"
#include "app/UpdateController.h"
#include "core/SettingsStore.h"
#include "dictation/DictationSession.h"
#include "frontend/mac/SpeecherBridge.h"

#import <AppKit/AppKit.h>

// Generated by swiftc from src/frontend/mac/swift, which is why the Swift target
// has to build before this one.
#import "SpeecherUI-Swift.h"

#include <QApplication>
#include <QDebug>
#include <QDesktopServices>
#include <QElapsedTimer>
#include <QFileOpenEvent>
#include <QStringList>
#include <QUrl>
namespace speecher {

namespace {

// Opening audio with Speecher from Finder, or dropping it on the Dock icon,
// arrives as a QFileOpenEvent: Qt's application delegate turns AppKit's
// application:openFiles: into one, and the Swift delegate proxy in
// SpeecherMacUI.swift forwards that selector to Qt's delegate. The files take
// the command line's route, so a file opened before setup is finished waits
// for setup the same way.
class FileOpenFilter final : public QObject {
public:
    explicit FileOpenFilter(ApplicationController *controller)
        : QObject(controller)
        , m_controller(controller)
    {
    }

    bool eventFilter(QObject *watched, QEvent *event) override
    {
        if (event->type() != QEvent::FileOpen) {
            return QObject::eventFilter(watched, event);
        }
        const QString path = static_cast<QFileOpenEvent *>(event)->file();
        if (!path.isEmpty()) {
            m_controller->showTranscribeFiles({path});
        }
        return true;
    }

private:
    ApplicationController *m_controller;
};

} // namespace

struct MacFrontEnd::Native {
    SpeecherBridge *bridge = nil;
    SpeecherMacUI *ui = nil;
};

MacFrontEnd::MacFrontEnd(ApplicationController *controller)
    : m_controller(controller)
    , m_native(std::make_unique<Native>())
{
    m_native->bridge = [[SpeecherBridge alloc] initWithController:controller];
    // The schema names the commands an Action row offers; what they do belongs
    // to the front end, as it does on Qt.
    m_native->bridge.settingsSchema.actionTriggered = ^(NSString *rowId) {
        const QString id = QString::fromNSString(rowId);
        if (id == QStringLiteral("runSetup")) {
            controller->showSetupAssistant();
            return;
        }
        if (id == QStringLiteral("checkForUpdates")) {
            controller->updates()->checkForUpdates(controller->settings()->updateChannel());
            return;
        }
        if (id == QStringLiteral("enableAccessibility")) {
            // The gate action on accessibility-gated rows: the same grant
            // flow the setup assistant runs. macOS answers with its own
            // consent prompt, so a failure here only means the prompt could
            // not be raised.
            QString error;
            if (!controller->enableAccessibility(&error)) {
                qWarning().noquote()
                    << "accessibility grant request failed message=" + error;
            }
            return;
        }
    };
    // The menu bar extra is the app's front door, so it exists from launch
    // rather than waiting for someone to ask for a window.
    m_native->ui = [[SpeecherMacUI alloc] initWithBridge:m_native->bridge];
    // What a Sparkle relaunch should put back on screen, captured right before
    // the process goes away. The tokens are main.cpp's. On-screen windows only,
    // never the microphone: the restart already waits for the session to
    // finish, and resuming what it waited out would record with no dictation
    // gesture behind it.
    // The provider outlives this front end on the controller's updater, so it
    // retains the UI object rather than reaching through the Native struct.
    SpeecherMacUI *ui = m_native->ui;
    controller->updates()->setRestoreStateProvider([ui] {
        QStringList state;
        if (ui.settingsWindowVisible) {
            state.append(QStringLiteral("settings"));
        }
        return state.join(QLatin1Char(','));
    });
    QObject::connect(controller->updates(),
                     &UpdateController::openReleasePageRequested,
                     controller,
                     [] {
                         QDesktopServices::openUrl(QUrl(QStringLiteral(
                             "https://github.com/firemonster612/speecher/releases")));
                     });
    // Parented to the controller, which goes first, so the filter never
    // reaches a controller that is gone.
    qApp->installEventFilter(new FileOpenFilter(controller));
}

MacFrontEnd::~MacFrontEnd()
{
    // An assistant left open holds callbacks into this front end and its
    // controller; closing it here is what the Qt front end's delete did.
    [m_native->ui dismissSetupAssistant];
}

// One window: the settings are all a Mac app puts in a window of its own, and
// dictation itself lives in the menu bar and the floating panel.
void MacFrontEnd::showMainWindow()
{
    [m_native->ui showSettings];
    // frontEndReady defers its work by a turn of the event loop, which is what
    // lets the window this call just ordered front draw first.
    m_controller->frontEndReady();
}

void MacFrontEnd::showSettingsWindow()
{
    showMainWindow();
}

// The page parameter is the Linux front end's: the only single page anyone asks
// for is its Global Shortcut page, which macOS does not have.
void MacFrontEnd::showSetupAssistant(SetupAssistantPage)
{
    MacFrontEnd *frontEnd = this;
    [m_native->ui showSetupAssistantWithCompletion:^{
        if (!frontEnd->m_controller->popupOnly()) {
            frontEnd->showMainWindow();
        }
    }];
}

void MacFrontEnd::showTranscribeFiles(const QStringList &paths)
{
    showMainWindow();
    NSMutableArray<NSString *> *files = [NSMutableArray arrayWithCapacity:NSUInteger(paths.size())];
    for (const QString &path : paths) {
        [files addObject:path.toNSString()];
    }
    [m_native->ui showTranscribeFiles:files];
}

bool MacFrontEnd::captureMainWindow(const QString &path)
{
    // SPEECHER_GRAB_PAGE=transcribe grabs the Transcribe pane, with any audio
    // files the command line named. As on Qt, SPEECHER_GRAB_CLICK=
    // transcribeStart starts them and SPEECHER_GRAB_WAIT_MS lets the batch
    // run before the grab.
    if (qEnvironmentVariable("SPEECHER_GRAB_PAGE").toLower() == QStringLiteral("transcribe")) {
        showTranscribeFiles({});
        if (qEnvironmentVariable("SPEECHER_GRAB_CLICK") == QStringLiteral("transcribeStart")) {
            [m_native->ui startTranscription];
        }
        // At least one pass, so SwiftUI draws the pane before the grab.
        QElapsedTimer waited;
        waited.start();
        const int waitMs = qEnvironmentVariableIntValue("SPEECHER_GRAB_WAIT_MS");
        do {
            QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
        } while (waited.elapsed() < waitMs);
    }
    return [m_native->ui captureSettingsToPath:path.toNSString()];
}

void MacFrontEnd::showDictationError(const QString &message)
{
    [m_native->ui showDictationProblem:message.toNSString()];
}

void MacFrontEnd::alert()
{
    QApplication::beep();
}

} // namespace speecher
