#include "frontend/mac/MacFrontEnd.h"

#include "app/ApplicationController.h"
#include "app/UpdateController.h"
#include "frontend/mac/SpeecherBridge.h"
#include "ui/SetupAssistant.h"

// Generated by swiftc from src/frontend/mac/swift, which is why the Swift target
// has to build before this one.
#import "SpeecherUI-Swift.h"

#include <QApplication>
namespace speecher {

struct MacFrontEnd::Native {
    SpeecherBridge *bridge = nil;
    SpeecherMacUI *ui = nil;
};

MacFrontEnd::MacFrontEnd(ApplicationController *controller)
    : m_controller(controller)
    , m_native(std::make_unique<Native>())
{
    m_native->bridge = [[SpeecherBridge alloc] initWithController:controller];
    // The schema names the commands an Action row offers; what they do belongs
    // to the front end, as it does on Qt.
    m_native->bridge.settingsSchema.actionTriggered = ^(NSString *rowId) {
        const QString id = QString::fromNSString(rowId);
        if (id == QStringLiteral("runSetup")) {
            controller->showSetupAssistant();
            return;
        }
        if (id == QStringLiteral("checkForUpdates")) {
            controller->updates()->checkForUpdates();
        }
    };
    // The menu bar extra is the app's front door, so it exists from launch
    // rather than waiting for someone to ask for a window.
    m_native->ui = [[SpeecherMacUI alloc] initWithBridge:m_native->bridge];
}

MacFrontEnd::~MacFrontEnd()
{
    // The assistant's accepted handler calls back into this front end, and a
    // top-level Qt window is not closed by anything else going away.
    delete m_setupAssistant.data();
}

// One window: the settings are all a Mac app puts in a window of its own, and
// dictation itself lives in the menu bar and the floating panel.
void MacFrontEnd::showMainWindow()
{
    [m_native->ui showSettings];
    // frontEndReady defers its work by a turn of the event loop, which is what
    // lets the window this call just ordered front draw first.
    m_controller->frontEndReady();
}

void MacFrontEnd::showSettingsWindow()
{
    showMainWindow();
}

void MacFrontEnd::showSetupAssistant()
{
    if (!m_setupAssistant) {
        m_setupAssistant = new SetupAssistant(m_controller);
        m_setupAssistant->setAttribute(Qt::WA_DeleteOnClose);
        QObject::connect(m_setupAssistant, &QDialog::accepted, m_setupAssistant, [this] {
            if (!m_controller->popupOnly()) {
                showMainWindow();
            }
        });
    }
    m_setupAssistant->show();
    m_setupAssistant->raise();
    m_setupAssistant->activateWindow();
}

bool MacFrontEnd::captureMainWindow(const QString &path)
{
    return [m_native->ui captureSettingsToPath:path.toNSString()];
}

void MacFrontEnd::showDictationError(const QString &message)
{
    [m_native->ui showDictationProblem:message.toNSString()];
}

void MacFrontEnd::alert()
{
    QApplication::beep();
}

} // namespace speecher
